### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by mattnap** [kalessil/phpinspectionsea#1416]
The plugin cannot be activated and forces the plugin to be deactivated before reboot.

For EA Ultimate 3.0.4.1

PhpStorm 2019.2.3
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Stack Trace
---
```
com.intellij.diagnostic.PluginException: Short name 'AmbiguousMethodsCallsInArrayMappingInspection' is not unique
class 'com.kalessil.phpStorm.phpInspectionsEA.inspectors.codeStyle.AmbiguousMethodsCallsInArrayMappingInspector' in PluginDescriptor(name=Php Inspections (EA Ultimate), classpath=/Library/Application Support/PhpStorm2019.2/PhpInspectionsUltimate.jar)
and
class'com.kalessil.phpStorm.phpInspectionsEA.inspectors.codeStyle.AmbiguousMethodsCallsInArrayMappingInspector' in PluginDescriptor(name=Php Inspections (EA Extended), classpath=/Library/Application Support/PhpStorm2019.2/PhpInspectionsEA.jar)
conflict [Plugin: com.kalessil.phpStorm.phpInspectionsUltimate]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.checkForDuplicateShortName(InspectionToolRegistrar.java:64)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.lambda$new$2(InspectionToolRegistrar.java:37)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:67)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:104)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$1(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.Preloader.lambda$componentsInitialized$2(Preloader.java:71)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kalessil** [comment]
Thank you for reporting @mattnap. Looks like both extended and ultimate plugins are getting installed. Extended needs to be uninstalled first, then the issue will go away.
