### ISSUE TITLE
TypeFromSignatureResolvingUtil.resolveSignature StackOverflowError

### ISSUE THREAD

**Issue by empi89** [kalessil/phpinspectionsea#143]
After installing the PHP Inspections EA Plugin on my PHP Storm installation the inspection stucks with now error in the UI (No suspicious code) on certain files. The idea.log provides the stacktrace below. I already tried to build up a minimal example to reproduce this error in a separate project. However, I am not able to reproduce the error after I close the project window with my original project. 

I have found a reference on this error in a source code file of this project [PhpInspectionsEAProvider.java](https://github.com/kalessil/phpinspectionsea/blob/2cf03442a82a4b3297c9734eaed3227e0214d7b1/src/main/java/com/kalessil/phpStorm/phpInspectionsEA/PhpInspectionsEAProvider.java#L6) but do not see any hint on how it was/is fixed.

How could I debug this problem? 

```
2017-02-14 17:07:28,762 [ 907711]  ERROR - aemon.impl.PassExecutorService - PhpStorm 2016.3.2  Build #PS-163.10504.2 
2017-02-14 17:07:28,762 [ 907711]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_112-release 
2017-02-14 17:07:28,762 [ 907711]  ERROR - aemon.impl.PassExecutorService - VM: OpenJDK 64-Bit Server VM 
2017-02-14 17:07:28,762 [ 907711]  ERROR - aemon.impl.PassExecutorService - Vendor: JetBrains s.r.o 
2017-02-14 17:07:28,762 [ 907711]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2017-02-14 17:07:28,762 [ 907711]  ERROR - aemon.impl.PassExecutorService - Last Action: CodeInspection.OnEditor 
2017-02-14 17:07:28,762 [ 907711]  ERROR - aemon.impl.PassExecutorService - null 
java.lang.StackOverflowError
	at com.intellij.util.IntSLRUCache.getCachedEntry(IntSLRUCache.java:52)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.getVFileName(FileNameCache.java:111)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:170)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:172)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:172)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:172)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:172)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:172)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:172)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getPath(VirtualFileSystemEntry.java:199)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getPath(PhpClassImpl.java:347)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.selectBestClass(PhpClassImpl.java:320)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClass(PhpClassImpl.java:315)
	at com.jetbrains.php.PhpClassHierarchyUtils.processMembersInternal(PhpClassHierarchyUtils.java:262)
	at com.jetbrains.php.PhpClassHierarchyUtils.processMethods(PhpClassHierarchyUtils.java:200)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getMethods(PhpClassImpl.java:210)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.TypeFromSignatureResolvingUtil.resolveSlot(TypeFromSignatureResolvingUtil.java:203)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.TypeFromSignatureResolvingUtil.resolveSignature(TypeFromSignatureResolvingUtil.java:130)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.TypeFromSignatureResolvingUtil.resolveSignature(TypeFromSignatureResolvingUtil.java:177)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.TypeFromSignatureResolvingUtil.resolveSignature(TypeFromSignatureResolvingUtil.java:177)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.TypeFromSignatureResolvingUtil.resolveSignature(TypeFromSignatureResolvingUtil.java:177)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.TypeFromSignatureResolvingUtil.resolveSignature(TypeFromSignatureResolvingUtil.java:177)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.TypeFromSignatureResolvingUtil.resolveSignature(TypeFromSignatureResolvingUtil.java:177)
```

**Comment by kalessil** [comment]
Uhh, not sure what to answer. You'd need to break inspections run down from top-level folders to individual files until you can find the file causing the issue.

IDE itself will not help locating the file in the case.

**Comment by empi89** [comment]
Thanks @kalessil, I already found a file that leads to this issue when I run the inspections on that file. I also reduced the code to one function that looks like this:
```
class Recursor
{
    public function getActualPriceRecursive()
    {

        $object = Factory::factory();
        
        $Price += $object->getPrice();

        return $Price;

    }
}
```

The error is gone when I use $Price = $Price + $object->getPrice(); instead. However when having the same code in a new project the error does only occur when the window of the regular project is still opened.

**Comment by kalessil** [comment]
And that's strange as types resolving by my plugin will not be invoked for this case. Any chance to get an unmodified file for experiments?

**Comment by kalessil** [comment]
I did adjustments on the plugin side: now it tracks which types combinations have been already resolved.
So infinity the exception should go away.

If it possible, I'd like to ask for testing the fixed plugin version (will provide instruction for installing it). Will this work for you @empi89 ?

**Comment by empi89** [comment]
@kalessil of course this will work, thanks!

**Comment by kalessil** [comment]
Great)

Step 1: [download](https://github.com/kalessil/phpinspectionsea/raw/master/PhpInspectionsEA.jar) dev-version of the plugin;
Step 2: In IDE 'Settings -> Plugins', under the list of plugins cleck 'Install plugin from disk' and take the downloaded file;
Step 3: restart IDE and inspect the file caused infinite inspection - the issue expected to be fixed now.

**Comment by empi89** [comment]
Works for me, thanks!

**Comment by kalessil** [comment]
Perfect, thank you for feedback @empi89
