### ISSUE TITLE
Short name 'AmbiguousMethodsCallsInArrayMappingInspection' is not unique

### ISSUE THREAD

**Issue by EmilCataranciuc** [kalessil/phpinspectionsea#1523]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.8
| Language level | e.g. PHP 7.4

Current behaviour
IDE Fatal Errors:
--
com.intellij.diagnostic.PluginException: Short name 'AmbiguousMethodsCallsInArrayMappingInspection' is not unique
class 'com.kalessil.phpStorm.phpInspectionsEA.inspectors.codeStyle.AmbiguousMethodsCallsInArrayMappingInspector' in PluginDescriptor(name=Php Inspections (EA Ultimate), classpath=/Users/furioussnail/Library/Application Support/PhpStorm2019.3/PhpInspectionsUltimate.jar)
and
class'com.kalessil.phpStorm.phpInspectionsEA.inspectors.codeStyle.AmbiguousMethodsCallsInArrayMappingInspector' in PluginDescriptor(name=Php Inspections (EA Extended), classpath=/Users/furioussnail/Library/Application Support/PhpStorm2019.3/PhpInspectionsEA.jar)
conflict [Plugin: com.kalessil.phpStorm.phpInspectionsUltimate]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.checkForDuplicateShortName(InspectionToolRegistrar.java:134)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.registerInspection(InspectionToolRegistrar.java:81)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.registerInspections(InspectionToolRegistrar.java:61)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.lambda$new$0(InspectionToolRegistrar.java:41)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:67)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:174)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.createTools(InspectionProfileImpl.java:459)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:481)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:110)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:476)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:110)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools$default(InspectionProfile.kt:103)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getAllTools(InspectionProfileImpl.java:770)
	at com.intellij.ide.ui.InspectionsTopHitProvider.getOptions(InspectionsTopHitProvider.java:31)
	at com.intellij.ide.ui.OptionsTopHitProvider.getCachedOptions(OptionsTopHitProvider.java:78)
	at com.intellij.ide.ui.OptionsTopHitProvider.access$600(OptionsTopHitProvider.java:39)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.lambda$cacheAll$2(OptionsTopHitProvider.java:267)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:292)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:157)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.cacheAll(OptionsTopHitProvider.java:263)
	at com.intellij.ide.ui.OptionsTopHitProvider$Activity.lambda$runActivity$0(OptionsTopHitProvider.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Expected behaviour
--

Environment details
---

**Comment by orklah** [comment]
I think it happened to me before when I kept the Extended plugin alongside Ultimate. Did you disable Extended?

**Comment by EmilCataranciuc** [comment]
> I think it happened to me before when I kept the Extended plugin alongside Ultimate. Did you disable Extended?

Thank you for the reply. It occurred to me later. Disabled the Extended plugin and will test it for a while.
