### ISSUE TITLE
[CRITICAL] Unable to load library error on M1 Macs

### ISSUE THREAD

**Issue by TimothyBJacobs** [kalessil/phpinspectionsea#1703]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | EA Ultimate 3.0.11 |
| Language level | PHP 7.0                        |

Current behaviour
--

The following error occurs on IDE startup. I no longer have an Intel based Mac to test to be sure, but I think this is an M1 error.

```
Unable to load library '/Users/timothybjacobs/Library/Caches/JetBrains/PhpStorm2020.3/tmp/php-inspections-ea-ultimate-20200703-1828/TurboActivate/mac/libTurboActivate.dylib': dlopen(/Users/timothybjacobs/Library/Caches/JetBrains/PhpStorm2020.3/tmp/php-inspections-ea-ultimate-20200703-1828/TurboActivate/mac/libTurboActivate.dylib, 9): no suitable image found. 

Did find: /Users/timothybjacobs/Library/Caches/JetBrains/PhpStorm2020.3/tmp/php-inspections-ea-ultimate-20200703-1828/TurboActivate/mac/libTurboActivate.dylib: no matching architecture in universal wrapper /Users/timothybjacobs/Library/Caches/JetBrains/PhpStorm2020.3/tmp/php-inspections-ea-ultimate-20200703-1828/TurboActivate/mac/libTurboActivate.dylib: no matching architecture in universal wrapper dlopen(/Users/timothybjacobs/Library/Caches/JetBrains/PhpStorm2020.3/tmp/php-inspections-ea-ultimate-20200703-1828/TurboActivate/mac/libTurboActivate.dylib, 9): no suitable image found. 

Did find: /Users/timothybjacobs/Library/Caches/JetBrains/PhpStorm2020.3/tmp/php-inspections-ea-ultimate-20200703-1828/TurboActivate/mac/libTurboActivate.dylib: no matching architecture in universal wrapper /Users/timothybjacobs/Library/Caches/JetBrains/PhpStorm2020.3/tmp/php-inspections-ea-ultimate-20200703-1828/TurboActivate/mac/libTurboActivate.dylib: no matching architecture in universal wrapper Native library (Users/timothybjacobs/Library/Caches/JetBrains/PhpStorm2020.3/tmp/php-inspections-ea-ultimate-20200703-1828/TurboActivate/mac/libTurboActivate.dylib) not found in resource path (/Applications/PhpStorm.app/Contents/lib/bootstrap.jar:/Applications/PhpStorm.app/Contents/lib/extensions.jar:/Applications/PhpStorm.app/Contents/lib/util.jar:/Applications/PhpStorm.app/Contents/lib/jdom.jar:/Applications/PhpStorm.app/Contents/lib/log4j.jar:/Applications/PhpStorm.app/Contents/lib/jna.jar)
```

Expected behaviour
--

To startup without error.

Environment details
---

```
PhpStorm 2020.3.1
Build #PS-203.6682.180, built on December 30, 2020
Licensed to Timothy Jacobs
Subscription is active until June 13, 2021.
Runtime version: 11.0.9.1+11-b1145.63 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.1
GC: ParNew, ConcurrentMarkSweep
Memory: 6077M
Cores: 8
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.tooltip.initialDelay=986
Non-Bundled Plugins: Quick Notes, Statistic, String Manipulation, com.intellij.ideolog, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, com.intellij.plugins.html.instantEditing, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsUltimate, com.ptby.dynamicreturntypeplugin, de.espend.idea.php.phpunit, de.espend.idea.php.behat, ru.adelf.idea.dotenv
```

**Comment by kalessil** [comment]
Ping @ea-inspections-team

**Comment by ea-inspections-team** [comment]
Fixed in 48a8d28b77e5c37ccab692b6633c638a19579684 //cc @kalessil

**Comment by ea-inspections-team** [comment]
A new release has been uploaded. Availability upon the update approval. //cc @kalessil

**Comment by meeprakash25** [comment]
I am getting the same error

**Comment by meeprakash25** [comment]
java.lang.IllegalStateException: You must not register toolwindow programmatically so early. Rework code or use ToolWindowManager.invokeLater
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.getDefaultToolWindowPaneIfInitialized(ToolWindowManagerImpl.kt:558)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow(ToolWindowManagerImpl.kt:1018)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.registerToolWindow(BackendServerToolWindowManager.kt:102)
	at com.intellij.openapi.wm.ToolWindowManager.registerToolWindow(ToolWindowManager.kt:37)
	at com.kalessil.phpStorm.phpInspectionsEA.EAUltimateSidebarComponent.projectOpened(EAUltimateSidebarComponent.java:46)
	at com.intellij.openapi.project.impl.ProjectManagerImplKt$runInitProjectActivities$$inlined$launchAndMeasure$2.invokeSuspend(startUpMeasurer.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:35)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by ea-inspections-team** [comment]
@meeprakash25, @TimothyBJacobs: from the reported details and comments, it seems that you was not contacted about migration to https://plugins.jetbrains.com/plugin/16935-php-inspections-ea-ultimate- and we are so sorry that this was not done timely.

Please contact us on [ea.inspections.team@gmail.com](mailto:ea.inspections.team@gmail.com) (we will arrange one year free license for you).
