### ISSUE TITLE
Cannot create extension (class=com.kalessil.phpStorm.phpInspectionsEA.indexers.NamedCallableParametersMetaIndexer)

### ISSUE THREAD

**Issue by controvi** [kalessil/phpinspectionsea#1774]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         |  Php Inspections (EA Ultimate), 4.0.6.4 |
| Language level | PHP 8.0.8                        |

Current behaviour
--
As soon as I start PHPStorm it gives the message that the plugin broke

Expected behaviour
--
Well.... that I don't get a error message 

Environment details
---
Error was happenign on both PHP Storm 2021.2.1 & PHP Storm 2021.2.2
Windows 10 & 11

PhpStorm 2021.2.2
Build #PS-212.5284.49, built on September 16, 2021
Licensed to XXX
Subscription is active until November 3, 2021.
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2040M
Cores: 12
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.kite.intellij (1.9.4), com.intellij.jira (3.6.0), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.4), com.kalessil.phpStorm.phpInspectionsUltimate-mp (2021.2), de.espend.idea.php.toolbox (6.0.0), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.212), ru.adelf.idea.dotenv (2021.3.0.212)

For completion, here is the error log.
Should more logs be needed, please let me know:

com.intellij.diagnostic.PluginException: Cannot create extension (class=com.kalessil.phpStorm.phpInspectionsEA.indexers.NamedCallableParametersMetaIndexer) [Plugin: com.kalessil.phpStorm.phpInspectionsUltimate-mp]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:932)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:88)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:458)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.access$200(ExtensionPointImpl.java:32)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$1.next(ExtensionPointImpl.java:365)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.initAssociatedDataForExtensions(FileBasedIndexDataInitialization.java:70)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.prepareTasks(FileBasedIndexDataInitialization.java:111)
	at com.intellij.util.indexing.IndexDataInitializer.call(IndexDataInitializer.kt:20)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.kalessil.phpStorm.phpInspectionsEA.indexers.NamedCallableParametersMetaIndexer (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Php Inspections (EA Ultimate), id=com.kalessil.phpStorm.phpInspectionsUltimate-mp, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PhpStorm2021.2\plugins\PhpInspectionsUltimate-mp.jar, version=2021.2, package=null), packagePrefix=null, instanceId=78, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:870)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.java:99)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:116)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:66)
	... 19 more
Caused by: java.lang.AssertionError: ID with name 'kalessil.phpStorm.phpInspectionsEA.callable_parameters' requested for plugin com.kalessil.phpStorm.phpInspectionsUltimate-mp but registered for com.kalessil.phpStorm.phpInspectionsEA plugin. Please use an instance field to access corresponding ID.
	at com.intellij.util.indexing.ID.findByName(ID.java:93)
	at com.intellij.util.indexing.ID.create(ID.java:67)
	at com.kalessil.phpStorm.phpInspectionsEA.indexers.NamedCallableParametersMetaIndexer.<clinit>(NamedCallableParametersMetaIndexer.java:30)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:482)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:830)
	... 22 more
Caused by: java.lang.Throwable
	at com.intellij.util.indexing.ID.<init>(ID.java:53)
	at com.intellij.util.indexing.ID.create(ID.java:68)
	... 26 more

**Comment by ea-inspections-team** [comment]
Thanks for reporting @controvi! It looks like you have the both Extended and Ultimate plugins installed, uninstalling the extedded one should fix the issue.
