### ISSUE TITLE
Exception in 2023.3

### ISSUE THREAD

**Issue by maicol07** [kalessil/phpinspectionsea#1912]
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) 2023.1 |
| Language level | JS project, no PHP                        |

Current behaviour
--
Exception is thrown when IDE is opened:
```
java.lang.ClassCastException: class javax.swing.ImageIcon cannot be cast to class com.intellij.openapi.util.ScalableIcon (javax.swing.ImageIcon is in module java.desktop of loader 'bootstrap'; com.intellij.openapi.util.ScalableIcon is in unnamed module of loader com.intellij.util.lang.PathClassLoader @ba4d54)
	at com.intellij.openapi.wm.impl.SquareStripeButton.updatePresentation(SquareStripeButton.kt:89)
	at com.intellij.toolWindow.ToolWindowPaneNewButtonManager$createStripeButton$manager$1.updateIcon(ToolWindowPaneNewButtonManager.kt:162)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.toolWindowPropertyChanged(ToolWindowManagerImpl.kt:2232)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.toolWindowPropertyChanged(BackendServerToolWindowManager.kt:318)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setIcon(ToolWindowImpl.kt:487)
	at com.kalessil.phpStorm.phpInspectionsEA.EAUltimateSidebarComponent.runActivity(EAUltimateSidebarComponent.java:48)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runOldActivity(StartupManagerImpl.kt:328)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runOldActivity(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$6.invoke$lambda$0(StartupManagerImpl.kt:284)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.project.SmartModeScheduler$addLast$1.invoke(SmartModeScheduler.kt:89)
	at com.intellij.openapi.project.SmartModeScheduler$addLast$1.invoke(SmartModeScheduler.kt:89)
	at com.intellij.openapi.project.SmartModeScheduler.addLast$lambda$0(SmartModeScheduler.kt:89)
	at com.intellij.openapi.project.SmartModeScheduler$RunnableDelegate.run(SmartModeScheduler.kt:49)
	at com.intellij.openapi.project.SmartModeScheduler.doRun(SmartModeScheduler.kt:138)
	at com.intellij.openapi.project.SmartModeScheduler.runAllWhileSmart(SmartModeScheduler.kt:130)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:857)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:477)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1444)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:862)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Expected behaviour
--
No exceptions

Environment details
---

```
PhpStorm 2023.3 EAP
Build #PS-233.11361.11, built on October 27, 2023
Licensed to PhpStorm EAP user: Maicol Battistini
Expiration date: November 26, 2023
Runtime version: 17.0.9+7-b1087.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.133.1-microsoft-standard-wsl2
GC: G1 Young Generation, G1 Old Generation
Memory: 6452M
Cores: 24
Registry:
  editor.focus.mode.color.light=d2d4d5
  ide.editor.tab.selection.animation=true
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  ide.balloon.shadow.size=0
  editor.focus.mode.color.dark=d2d4d5
Non-Bundled Plugins:
  com.github.patou.gitmoji (1.13.0)
  com.github.lppedd.idea-conventional-commit (0.22.0)
  com.fwdekker.randomness (2.7.7)
  com.github.weisj.darkmode (1.8.0-2023.3)
  com.github.exidcuter.dockerregistryexplorer (1.1.0-stable)
  dev.meanmail.plugin.nginx-intellij-plugin-pro (2022.1.1)
  com.nasller.CodeGlancePro (1.7.6-SNAPSHOT-2023-09-26T23-40)
  com.obroom.plugin.smartsearch (2023.10.1)
  awesome.console (0.1337.12)
  com.renemaas.intellij.zipper (1.1.0)
  com.obroom.plugin.toolset (2023.10.1)
  com.github.copilot (1.3.3.3572)
  org.jetbrains.plugins.stylus (233.11361.11)
  com.khmelyuk.multirun (1.13)
  com.intellij.ideolog (222.1.0.0)
  String Manipulation (9.11.3)
  siosio.EmojiCommitLogViewer (1.0.7)
  com.shuzijun.markdown-editor (2.0.5)
  lermitage.intellij.extra.icons (2023.2.12-231)
  com.github.camork.fileExpander (2.3)
  hu.hawser.co-author-plugin (2.3)
  com.wakatime.intellij.plugin (14.2.3)
  com.github.shiraji.emoji (3.1.0)
  GrepConsole (12.22.1-IJ2021.1)
  com.intellij.grazie.pro (0.3.261)
  pro.bashsupport (3.3.3.233)
  com.github.yunabraska.githubworkflowplugin (3.1.0)
  com.intellij.ml.llm (233.11361.11)
  com.virtuslab.git-machete (4.1.0)
  com.github.jk1.ytplugin (2023.1.64)
  mdx.js (233.11361.11)
  de.sist.gitlab (2.14.2)
  zielu.gittoolbox (500.0.22+222)
  mobi.hsz.idea.gitignore (4.5.2)
  com.intellij.plugins.html.instantEditing (233.11361.11)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  com.funivan.idea.phpClean (2023.04.01)
  lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
  ru.adelf.idea.dotenv (2023.3)
  NEON support (0.5.4)
  nl.deschepers.laraveltinker (2.6.1)
  net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0)
  com.kalessil.phpStorm.phpInspectionsUltimate-mp (2023.1)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (9.4.0)
  fr.adrienbrault.idea.symfony2plugin (2022.1.259)
  de.espend.idea.php.drupal (0.6.0)
  org.masamotod.idea.Drupal8NamespaceDetector (1.0)
  net.rentalhost.plugins.php.hammer (0.27.0)
  org.endpointdeps.EndpointDependencies (1.3)
  dev.nybroe.collector (0.4.0)
  com.laravel_idea.plugin (7.4.3.233)
  com.mallowigi (94.1.0)
Current Desktop: Undefined
```

**Comment by ea-inspections-team** [comment]
Duplicates #1923 (the issue has been addressed).
