### ISSUE TITLE
[Tests] Unregistered inspections requested

### ISSUE THREAD

**Issue by Garethp** [kalessil/phpinspectionsea#213]
I had to set up a new machine due to hardware issues, and when I try to run any tests, I get this error

```
java.lang.RuntimeException: Unregistered inspections requested: [com.kalessil.phpStorm.phpInspectionsEA.inspectors.languageConstructions.ParameterByRefWithDefaultInspector]

	at com.intellij.testFramework.InspectionTestUtil.instantiateTools(InspectionTestUtil.java:183)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.enableInspections(CodeInsightTestFixtureImpl.java:361)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.enableInspections(CodeInsightTestFixtureImpl.java:356)
	at com.kalessil.phpStorm.phpInspectionsEA.ParameterByRefWithDefaultInspectorTest.testIfFindsAllPatterns(ParameterByRefWithDefaultInspectorTest.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.intellij.testFramework.UsefulTestCase.lambda$runTest$10(UsefulTestCase.java:311)
	at com.intellij.testFramework.UsefulTestCase.lambda$invokeTestRunnable$11(UsefulTestCase.java:343)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:40)
	at com.intellij.testFramework.UsefulTestCase.invokeTestRunnable(UsefulTestCase.java:342)
	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:330)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:356)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$1.run(EdtTestUtil.kt:46)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:165)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

For each test (Obviously each test failing on the inspection it's trying to test). I'm not sure what's going on, I had my settings set up right. Have you seen something like this?

**Comment by kalessil** [comment]
Looks like resources folder is not recognized, so ParameterByRefWithDefaultInspector considered as not register (I guess all of then actually).

Do you have the same layout as here: https://github.com/kalessil/phpinspectionsea/blob/master/docs/images/module-settings.png ?
Folders near the selection at screenshot have different icons.

**Comment by Garethp** [comment]
It was set like that. I solved it, somehow. I'm not sure how or why, but swapping from Community to Ultimate seems to have performed some voodoo magic that lets my tests run.
