### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by maxmedvedev** [kalessil/phpinspectionsea#406]
PhpStorm 172.3317
```
 java.lang.StackOverflowError
	at com.jetbrains.php.lang.psi.PhpFileImpl.getMainNamespaceName(PhpFileImpl.java:243)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.findNamespaceName(PhpReferenceImpl.java:189)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getNamespaceName(PhpReferenceImpl.java:158)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.resolveLocal(ClassReferenceImpl.java:189)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.getFQN(ClassReferenceImpl.java:313)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperFQN(PhpClassImpl.java:298)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSuperClass(PhpClassImpl.java:309)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.getSupers(PhpClassImpl.java:645)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:77)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:80)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:80)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:80)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:80)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:80)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:80)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:80)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:80)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
<...>
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveInheritDoc(ThrowsResolveUtil.java:80)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.phpDoc.ThrowsResolveUtil.resolveThrownExceptions(ThrowsResolveUtil.java:60)
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.exceptions.ExceptionsAnnotatingAndHandlingInspector$1.visitPhpMethod(ExceptionsAnnotatingAndHandlingInspector.java:102)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:81)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:70)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:282)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:250)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:250)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by kalessil** [comment]
Ouch, thanks for reporting @maxmedvedev
