### ISSUE TITLE
Feature Idea: Release Notes / Update Notes in PHPStorm Event Log

### ISSUE THREAD

**Issue by tfettig01** [kalessil/phpinspectionsea#56]
I'm always looking to find out what changed between versions of the EA plugin and it sometimes takes me a while to finally get to https://plugins.jetbrains.com/update/index?pr=&updateId=30402 or something similar to see what updates happened

As it happens I was updating the .ignore plugin to v1.6 at the same time as EA Inspections and noticed that they added the following into the Event Log:

10:27 AM	.ignore plugin updated to v1.6
Features:
  - Unignore Files (250)
  - Default icon for .ignore files (258)
  - StyleLint (.stylelintignore) support (241)
  Fixes:
  - ...
  - NoSuchMethodError: com.intellij.util.contain... (show balloon)

The plugin is at https://github.com/hsz/idea-gitignore.

It would be nice to have something similar for EA. If the risk of cluttering the event log was too great then even a link to the update notes in the Event Log would be great.

**Comment by tfettig01** [comment]
I just got the latest update. The change made it real easy to see what changed, and what to keep an eye out for.

Thank you for all your work.

**Comment by kalessil** [comment]
You are welcome, I actually thought "Why I didn't do it yet?" when saw your ticket.
Thank you for a great proposal)

**Comment by tfettig01** [comment]
Hum, I missed this in the IDE Fatal Error logs.

Component name collision: UpdateComponent class mobi.hsz.idea.gitignore.UpdateComponent and class com.kalessil.phpStorm.phpInspectionsEA.UpdateComponent

Here is the thread details.

Component name collision: UpdateComponent class mobi.hsz.idea.gitignore.UpdateComponent and class com.kalessil.phpStorm.phpInspectionsEA.UpdateComponent
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:432)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.access$300(ComponentManagerImpl.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:492)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:284)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:222)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:463)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:572)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kalessil** [comment]
I created a separate ticket for the exception
