### ISSUE TITLE
Exception encountered while opening file

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#616]
Just ran into this when opening a test file

```
com.jetbrains.php.codeInsight.controlFlow.instructions.PhpExitPointInstruction.getPredecessors()Ljava/util/Collection;
java.lang.NoSuchMethodError: com.jetbrains.php.codeInsight.controlFlow.instructions.PhpExitPointInstruction.getPredecessors()Ljava/util/Collection;
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.codeStyle.MultipleReturnStatementsInspector$1.visitPhpMethod(MultipleReturnStatementsInspector.java:48)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:85)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1132)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:234)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.NoSuchMethodError: com.jetbrains.php.codeInsight.controlFlow.instructions.PhpExitPointInstruction.getPredecessors()Ljava/util/Collection;
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.codeStyle.MultipleReturnStatementsInspector$1.visitPhpMethod(MultipleReturnStatementsInspector.java:48)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:85)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1132)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:234)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

The file was

```
<?php

/**
 * @param string $objId
 *
 * @return string[][]|false
 */
function queryDatabase($objId) {
    return [ [ "20" ] ];
}

/**
 * @param int $objId
 *
 * In my codebase the at-return is red-squiggle-underlined with "return type does not match" because we're possibly returning
 * The int $objId parameter.  Even in this test the $objId on the return line is tagged as an int when you cmd-hover.
 * @return string  Final object id
 */
function usesDBQuery($objId) {

    $temp = queryDatabase($objId);
    if (is_array($temp)) {
        // Flagged with "$temp may not support offset operations (EA Extended).  I'll ask them if there's a way to
        // get PhpStorm to know that at this point it's going to be an array?
        // With the code like this there is no return-type inspection triggered.
        // Thinking about this some more I would have expected an additional string not in annotated types (int)
        // inspection here too.
        $objId = $temp[0][0];

        // If I cast $temp to an array then the offset inspection goes away and the return line is highlighted with 
        // "Return value is expected to be 'string', 'int' returned.  Is it an EA Extended problem that's preventing
        // the PhpStorm inspection on the return or a PhpStorm issue?
        // $objId = ((array)$temp)[0][0];
    }

    // In my codebase the return is not highlighted in any way even though the at-return is red-squiggle-underlined
    return $objId;

}

/**
 * @return string
 */
function testSimpleReturnType() {
    $x = 5;
    // Return value expected to be string, int returned
    return $x;
}

/**
 * @return string
 */
function testComplexReturnType() {
    $x = 5;
    if (false) {
        $x = "5";
    }
    // No warning
    return $x;
}
```

PhpStorm 2017.3 EAP
Build #PS-173.3415.21, built on October 25, 2017
PhpStorm EAP User
Expiration date: November 24, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

Php Inspections EA Extended 2.3.1.11

**Comment by kalessil** [comment]
Please temporary disable multiple return statements inspection - PS team reverted the change caused this exception + 2.3.12 has temp workaround for the period of EAP stabilization.
