### ISSUE TITLE
OpeanapiEquivalenceUtil.areEqual must not be null

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#736]
```php
if ($bungieUserClan &&
!\in_array()) { // <-- happen here while I am typing
    $bungieUserClan = null;
}
```

```
Argument for @NotNull parameter 'second' of com/kalessil/phpStorm/phpInspectionsEA/utils/OpeanapiEquivalenceUtil.areEqual must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'second' of com/kalessil/phpStorm/phpInspectionsEA/utils/OpeanapiEquivalenceUtil.areEqual must not be null
	at com.kalessil.phpStorm.phpInspectionsEA.utils.OpeanapiEquivalenceUtil.$$$reportNull$$$0(OpeanapiEquivalenceUtil.java)
	at com.kalessil.phpStorm.phpInspectionsEA.utils.OpeanapiEquivalenceUtil.areEqual(OpeanapiEquivalenceUtil.java)
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.languageConstructions.UnnecessaryEmptinessCheckInspector$1.lambda$group$6(UnnecessaryEmptinessCheckInspector.java:234)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1569)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.languageConstructions.UnnecessaryEmptinessCheckInspector$1.group(UnnecessaryEmptinessCheckInspector.java:234)
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.languageConstructions.UnnecessaryEmptinessCheckInspector$1.visitPhpBinaryExpression(UnnecessaryEmptinessCheckInspector.java:82)
	at com.jetbrains.php.lang.psi.elements.impl.BinaryExpressionImpl.accept(BinaryExpressionImpl.java:55)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:70)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:286)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:254)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:223)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by kalessil** [comment]
Got it, also crash reports the same.
