### ISSUE TITLE
Short name 'ForgottenDebugOutputInspection' is not unique exception

### ISSUE THREAD

**Issue by fabioi** [kalessil/phpinspectionsea#769]
Hi 

on PhpStorm 2017.3 just got this exception:

Short name 'ForgottenDebugOutputInspection' is not unique
class 'com.kalessil.phpStorm.phpInspectionsEA.inspectors.apiUsage.debug.ForgottenDebugOutputInspector' in PluginDescriptor[name='Php Inspections (EA Ultimate)', classpath='/Users/fabio/Library/Application Support/PhpStorm2017.3/PhpInspectionsUltimate.jar']
and
class'com.kalessil.phpStorm.phpInspectionsEA.inspectors.apiUsage.debug.ForgottenDebugOutputInspector' in PluginDescriptor[name='Php Inspections (EA Extended)', classpath='/Users/fabio/Library/Application Support/PhpStorm2017.3/PhpInspectionsEA.jar']
conflict [Plugin: com.kalessil.phpStorm.phpInspectionsUltimate]
com.intellij.diagnostic.PluginException: Short name 'ForgottenDebugOutputInspection' is not unique
class 'com.kalessil.phpStorm.phpInspectionsEA.inspectors.apiUsage.debug.ForgottenDebugOutputInspector' in PluginDescriptor[name='Php Inspections (EA Ultimate)', classpath='/Users/fabio/Library/Application Support/PhpStorm2017.3/PhpInspectionsUltimate.jar']
and
class'com.kalessil.phpStorm.phpInspectionsEA.inspectors.apiUsage.debug.ForgottenDebugOutputInspector' in PluginDescriptor[name='Php Inspections (EA Extended)', classpath='/Users/fabio/Library/Application Support/PhpStorm2017.3/PhpInspectionsEA.jar']
conflict [Plugin: com.kalessil.phpStorm.phpInspectionsUltimate]
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:86)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.a(InspectionToolRegistrar.java:60)
	at com.intellij.codeInspection.ex.InspectionToolRegistrar.createTools(InspectionToolRegistrar.java:127)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:34)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kalessil** [comment]
Hi Fabio, looks like it's phpStorm EAP version, am I right?

Stable builds prompting a dialog that Extended-plugin needs to be uninstalled and EAP reports this and preventing the dialog to appear.

**Comment by fabioi** [comment]
Hi @kalessil I think you are right, I am switching back and forth from PHPStorm 2017.3 to 2018.1 EAP.  Got no exceptions on PHPStorm 2017.3.

**Comment by kalessil** [comment]
👍
