### ISSUE TITLE
Add a quick "Getting Started" for developers

### ISSUE THREAD

**Issue by tomzx** [kalessil/phpinspectionsea#8]
I think it would be very useful for anyone interested in participating in the development of `phpinspectionea` if there were a small section of the `README.md` dedicated to setting up Intellij IDEA to create and debug new inspections and intentions.
- Setting up Intellij for development
- Running tests

**Comment by kalessil** [comment]
Will do that. 

What I'm not sure about is the format: plain Markdown or PDF with screenshots. Any preferences here?

**Comment by funivan** [comment]
+1 for the markdown =)

**Comment by tomzx** [comment]
Markdown with screenshots :smile:.

Minimally plain markdown, if it can be augmented with images, even better.

**Comment by kalessil** [comment]
This has to wait until next week, while I working out feedback from the last update.

PS: I can create several tickets to state fields "in fire" where contribution would help and doesn;t require complete dev. environment.

**Comment by kalessil** [comment]
Okay, new release is out - now back to this

**Comment by kalessil** [comment]
Almost done here, will be available next week.

**Comment by tomzx** [comment]
@kalessil Any update on this? I see https://github.com/kalessil/phpinspectionsea/blob/master/docs/DEVELOPERS.md but it's missing the images.

**Comment by kalessil** [comment]
Not yet: I was increasing tests coverage instead, sorry for not providing any feedback.
I'll ping you once screenshots has been pushed.

**Comment by tomzx** [comment]
@kalessil I've gone through most of the inspections at this point to correct wording/sentences and to attempt to normalize formatting. I'd like to be able to send you a PR for that, however I'm still unable to run the test suites and I'm waiting to see if your updated documentation will help me out with that.

I'm mainly getting the following error when I run the actual test suite, would you have any idea as to why?

Thanks!

```
java.lang.RuntimeException: java.lang.RuntimeException: Could not initialize class com.sun.proxy.$Proxy55

	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:189)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:655)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:660)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:37)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:28)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.UsefulTestCase.runBare(UsefulTestCase.java:431)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: Could not initialize class com.sun.proxy.$Proxy55
	at com.intellij.openapi.ui.TestDialog$1.show(TestDialog.java:23)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:258)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:283)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:294)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:719)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.newProject(ProjectManagerImpl.java:186)
	at com.intellij.testFramework.PlatformTestCase.createProject(PlatformTestCase.java:257)
	at com.intellij.testFramework.fixtures.impl.HeavyIdeaTestFixtureImpl.setUpProject(HeavyIdeaTestFixtureImpl.java:153)
	at com.intellij.testFramework.fixtures.impl.HeavyIdeaTestFixtureImpl.setUp(HeavyIdeaTestFixtureImpl.java:94)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$setUp$7(CodeInsightTestFixtureImpl.java:1197)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:28)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:26)
	at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$b0f40f3d.run(EdtTestUtil.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:647)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:660)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:37)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:28)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.setUp(CodeInsightTestFixtureImpl.java:1196)
	at com.intellij.testFramework.fixtures.CodeInsightFixtureTestCase.setUp(CodeInsightFixtureTestCase.java:49)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:372)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:28)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:26)
	at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$b0f40f3d.run(EdtTestUtil.kt)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:166)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by kalessil** [comment]
@tomzx : difficult to say, the problem seems to be with class-loading.

Can you post here how `File -> Project Settings -> Libraries` and `File -> Project Settings -> SDKs` are looking in Idea?

**Comment by tomzx** [comment]
As requested:

![idea_2017-01-01_14-04-39](https://cloud.githubusercontent.com/assets/188960/21582556/6d42d88e-d02b-11e6-91ef-24ab38b3cd25.png)
![idea_2017-01-01_14-05-46](https://cloud.githubusercontent.com/assets/188960/21582555/6d403110-d02b-11e6-8227-bbc2b1fb4a82.png)

**Comment by kalessil** [comment]
Idea Ultimate is required for running tests, what is your email (I'll send you a license)?

**Comment by tomzx** [comment]
Alright, thanks for the pointer, it works now! (no need for a license, I already have one, thanks anyways!)

**Comment by kalessil** [comment]
Great, thanks for an update)

**Comment by kalessil** [comment]
Developers documentation has been updated in #207.
