### ISSUE TITLE
issue while trying to apply fixes

### ISSUE THREAD

**Issue by mitelg** [kalessil/phpinspectionsea#932]
today I got this error message while I wanted to apply a suggested fix. Unfortunately I didn't recognize it immediately, so I don't know, what I did exactly. 

> QuickFix-es with the same family name (Merge into parent construct) should be the same class instances but actually are com.kalessil.phpStorm.phpInspectionsEA.inspectors.ifs.NestedPositiveIfStatementsInspector$MergeIntoParentElseFix and com.kalessil.phpStorm.phpInspectionsEA.inspectors.ifs.NestedPositiveIfStatementsInspector$MergeIntoParentIfFix instances. Please assign reported exception for the inspection "class com.kalessil.phpStorm.phpInspectionsEA.inspectors.ifs.NestedPositiveIfStatementsInspector" ("NestedPositiveIfStatementsInspection") developer.
java.lang.AssertionError: QuickFix-es with the same family name (Merge into parent construct) should be the same class instances but actually are com.kalessil.phpStorm.phpInspectionsEA.inspectors.ifs.NestedPositiveIfStatementsInspector$MergeIntoParentElseFix and com.kalessil.phpStorm.phpInspectionsEA.inspectors.ifs.NestedPositiveIfStatementsInspector$MergeIntoParentIfFix instances. Please assign reported exception for the inspection "class com.kalessil.phpStorm.phpInspectionsEA.inspectors.ifs.NestedPositiveIfStatementsInspector" ("NestedPositiveIfStatementsInspection") developer.
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.ifs.NestedPositiveIfStatementsInspector$1.visitPhpIf(NestedPositiveIfStatementsInspector.java:67)
	at com.jetbrains.php.lang.psi.elements.impl.IfImpl.accept(IfImpl.java:50)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:301)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:223)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by kalessil** [comment]
Hi @mitelg, would you please check which Php Inspections plugins you have installed (if both Extended and Ultimate, then it worth uninstalling the Extended one)

**Comment by kalessil** [comment]
Any news @mitelg ?

**Comment by mitelg** [comment]
Hi @kalessil 
sorry for the delay. I was on a business trip.
I've only installed `Php Inspections (EA Extended)` Version: 3.0.3

**Comment by kalessil** [comment]
Weird, and which IDE version is it?

**Comment by kalessil** [comment]
Fixed! Also please ask Hendrik Söbbing for a license for Php Inspections (EA Ultimate) - hopefully, some of the licenses are available.

**Comment by mitelg** [comment]
thanks a lot :+1: :blush: 
I will ask him :smile:
