### ISSUE TITLE
After update exception: java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId

### ISSUE THREAD

**Issue by davidmpaz** [kalessil/phpinspectionsea#944]
Hi,

after some time out of the PC, i did a suggested update of the plugin. Then started to get the exception below.

I already did an `Invalidate Cache / Restart` in PhpStorm.

PhpStorm info:
```
PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-41-generic
```

Thanks in advance,
Cheers

```
com/intellij/util/indexing/IndexId
java.lang.NoClassDefFoundError: com/intellij/util/indexing/IndexId
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.TransitiveDependenciesUsageInspector$1.getManifest(TransitiveDependenciesUsageInspector.java:81)
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.TransitiveDependenciesUsageInspector$1.visitPhpClassReference(TransitiveDependenciesUsageInspector.java:56)
	at com.jetbrains.php.lang.psi.elements.impl.ClassReferenceImpl.accept(ClassReferenceImpl.java:45)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:282)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:250)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:222)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:151)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:222)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:151)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:222)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: com.intellij.util.indexing.IndexId PluginClassLoader[com.kalessil.phpStorm.phpInspectionsUltimate, 2.0.5]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
```

**Comment by kalessil** [comment]
Fixed (hopefully).
