### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#962]
Reported element PsiElement(variable) is not from the file 'PHP file' the inspection 'PropertyCanBeStaticInspection' (class com.kalessil.phpStorm.phpInspectionsEA.inspectors.semanticalAnalysis.classes.PropertyCanBeStaticInspector) was invoked for. Message: 'This property initialization seems to be quite 'heavy', consider using static property or constant instead.'.
Element' containing file: PHP file
Inspection invoked for file: PHP file
 [Plugin: com.kalessil.phpStorm.phpInspectionsUltimate]
com.intellij.diagnostic.PluginException: Reported element PsiElement(variable) is not from the file 'PHP file' the inspection 'PropertyCanBeStaticInspection' (class com.kalessil.phpStorm.phpInspectionsEA.inspectors.semanticalAnalysis.classes.PropertyCanBeStaticInspector) was invoked for. Message: 'This property initialization seems to be quite 'heavy', consider using static property or constant instead.'.
Element' containing file: PHP file
Inspection invoked for file: PHP file
 [Plugin: com.kalessil.phpStorm.phpInspectionsUltimate]
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:520)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:479)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:236)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.doInspectInBatch(LocalInspectionsPass.java:151)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.a(GlobalInspectionContextImpl.java:552)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.a(GlobalInspectionContextImpl.java:435)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:94)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:138)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:131)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:94)
	at com.intellij.openapi.project.DumbService.tryRunReadActionInSmartMode(DumbService.java:112)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.a(GlobalInspectionContextImpl.java:426)
	at com.intellij.concurrency.JobLauncherImpl$1MyTask.a(JobLauncherImpl.java:300)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.JobLauncherImpl$1MyTask.call(JobLauncherImpl.java:287)
	at com.intellij.concurrency.JobLauncherImpl$1MyTask.call(JobLauncherImpl.java:277)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by kalessil** [comment]
`public void visitPhpClass()` gets fired for PhpClassAlias node
