### ISSUE TITLE
Exception: ...character to be escaped is missing...

### ISSUE THREAD

**Issue by wolfheart** [kalessil/phpinspectionsea#975]
Running PHPStorm 2018.1.6 and PHP Inspections (EA Extended) 3.0.5 from time to time there is this exception:

```
character to be escaped is missing
java.lang.IllegalArgumentException: character to be escaped is missing
	at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replaceAll(String.java:2223)
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.languageConstructions.StaticInvocationViaThisInspector$1.handleLateStaticBinding(StaticInvocationViaThisInspector.java:83)
	at com.kalessil.phpStorm.phpInspectionsEA.inspectors.languageConstructions.StaticInvocationViaThisInspector$1.visitPhpMethodReference(StaticInvocationViaThisInspector.java:65)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:31)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
```

From there on, there different backtraces...

**Comment by kalessil** [comment]
Thank you for reporting @wolfheart, I'll take care about the issue. Hot-fix release will follow shortly

**Comment by kalessil** [comment]
Fixed!

**Comment by wolfheart** [comment]
Wow, that was fast! Thx! 👍
